#!/bin/bash

# VPN-SimpleSetup -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Change the passphrase for a key.

# get system variables if needed
. ./vars

usage (){
    printf "
Usage: $0 key_name

List of key files:
------------------\n"
    find $SETUP_DIR/easyrsa3/pki/private/*  -printf "%f\n"
}

# STEP 1 - check if the right number of parameters were supplied.
if [ $# -lt 1 ] ; then
    usage
    exit 1
fi

# STEP 2 - Drop extension to key file if supplied
KEY="${1//.key}"

# STEP 3 - Change Passphrase
cd ./easyrsa3/pki/private
openssl rsa -aes256 -in $KEY.key -out $KEY.new
if [ $? -eq 0 ] ; then
    shred $KEY.key
    mv $KEY.new $KEY.key
fi

cd $SETUP_DIR
