#!/bin/bash

# VPN-Admin -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Revoke and delete client or server key/certificates and configs

# get system variables
. ./vars

# make sure there is a Certificate Authority for this system.
ca_check

usage (){
    printf "
Usage: $0 certificate_common_name

List of certificate files:
--------------------------\n"
    if [ "$(ls -A $SETUP_DIR/easyrsa3/pki/issued)" ]; then
        find $SETUP_DIR/easyrsa3/pki/issued/*  -printf "%f\n"
    fi       
}

# STEP 1 - check if the right number of parameters were supplied.
if [ $# -lt 1 ] ; then
    usage
    exit 1
fi

# STEP 2 - Drop extension to certificate if supplied
CERT="${1//.crt}"


# STEP 3 - Does Certificate Exist
if [ ! -f ./easyrsa3/pki/issued/$CERT.crt ] ; then
   printf "Error: Certificate file not found.\n"
   exit 1
fi

# STEP 4 - Revoke Certificate
printf "Removing certificate $CERT.crt\n"
cd ./easyrsa3/
./easyrsa revoke $CERT
r1=$?
cd ..

# STEP 5 - If revoke succssful then rename certificate and delete private key and request
if [ $r1 -eq 0 ] ;
    then
        if [ ! -d ./easyrsa3/pki/revoked ] ; then
            mkdir ./easyrsa3/pki/revoked
        fi
        printf "OK: Certificate $CERT has been revoked.\n"
        cd ./easyrsa3/pki
        cp --backup=numbered issued/$CERT.crt revoked/$CERT.revoked.crt
        rm issued/$CERT.crt
        rm private/$CERT.key
        rm reqs/$CERT.req
        cd ../..
    else
        printf "Error: A certificate removal problem occured.\n"
        exit 1
fi

# STEP 6 - Look for and remove config files.
if [ -f ./clients/$CERT.conf ] ; then
    printf "Deleting ./clients/$CERT.conf\n"
    rm ./clients/$CERT.conf
fi

if [ -f ./clients/$CERT.ovpn ] ; then
    printf "Deleting ./clients/$CERT.ovpn\n"
    rm ./clients/$CERT.ovpn
fi

if [ -f ./servers/$CERT.conf ] ; then
    printf "Deleting ./servers/$CERT.conf\n"
    rm ./servers/$CERT.conf
fi

if [ -f ./servers/$CERT.ovpn ] ; then
    printf "Deleting ./servers/$CERT.ovpn\n"
    rm ./servers/$CERT.ovpn
fi
