#!/bin/bash

# VPN-SimpleSetup -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Erase keys from system.  

# get system variables if needed
. ./vars

# STEP1 - Make sure the keys are to be erased.
verify "Have you made a backup?  (Yes/No) > "
if [ 0 != $? ] ; then 
    printf "\nRun ./update-thumbdrive to make backup.\n"
    exit 1 
fi

verify "Are you sure you want to remove the keys on this system (Yes/No) > "
if [ 0 != $? ] ; then 
    exit 1 
fi

# STEP2 - Erase the keys
find ./clients -type f -exec shred -u {} \;
find ./servers -type f -exec shred -u {} \;
find ./easyrsa3/pki/private -type f -exec shred -u {} \;
shred -u ./easyrsa3/pki/ta.key
