#!/bin/bash

# VPN-Admin -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# View the various certificates in readable format.

# get system variables if needed
. ./vars

# make sure there is a Certificate Authority for this system.
ca_check

function view_issued_certificate {
    if [ ${1:(-4)} == ".crt" ] ; 
        then
            fn=$1
        else
            fn="$1.crt"
    fi
    openssl x509 -in ./easyrsa3/pki/issued/$fn -text 
    return 0
}

function view_configuration {
    if [ ${1:(-5)} == ".conf" ] ; 
        then
            fn=$1
        else
            fn="$1.conf"
    fi
    echo "File is $fn"
    if [ -f $SETUP_DIR/servers/$fn ] ; then
        cat $SETUP_DIR/servers/$fn
    fi
    
    if [ -f $SETUP_DIR/clients/$fn ] ; then
        cat $SETUP_DIR/clients/$fn 
    fi

    return 0
}

# STEP 1 - check if the right number of parameters were supplied.
if  [ "$1" != "ca" ] && [ "$1" != "cert" ] && [ "$1" != "conf" ] && [ "$1" != "crl" ]  ;
    then
        printf "
Usage: $0 ca|crt|crl
          ca - View the Certificate Authority
         crl - View the certificate revokation list
        cert - View a list of certificates issued
   cert name - View a specific certificate
        conf - View a list of configuration files
   conf name - View a specific certificate\n"
        exit 1
fi

# VIEW CA - View the Certificate Authority
if [ "$1" == "ca" ] ; 
    then
        openssl x509 -in ./easyrsa3/pki/ca.crt -text
        exit 0
fi

# VIEW CRL - View the Certificate Authority
if [ "$1" == "crl" ] ; 
    then
        if [ -f $SETUP_DIR/easyrsa3/pki/crl.pem ] ; then
            openssl crl -in ./easyrsa3/pki/crl.pem -noout -text
        else
            printf "
The certificate revokation list has not been created yet.
Run ./create-crl to generate list.\n"
        fi    
        exit 0
fi

# VIEW CERT - View the Certificate
if [ "$1" == "cert" ] ; then
    if [ "$2" == "" ] ; then
        printf "
Current certificate files:
--------------------------\n"
        cd ./easyrsa3/pki/issued
        if [ "$(ls -A $SETUP_DIR/easyrsa3/pki/issued)" ]; then
            find $SETUP_DIR/easyrsa3/pki/issued/*  -printf "%f\n"
        fi       
        cd $SETUP_DIR
        exit 0
    else
        view_issued_certificate $2
        exit 
    fi
fi

# VIEW CONF - View configuration files.
if [ "$1" == "conf" ] ; then
    if [ "$2" == "" ] ; then
        printf "
Current configuration files:
----------------------------\n"
        if [ -d "$SETUP_DIR/servers" ] ; then
            cd $SETUP_DIR/servers
            if [ "$(ls -A $SETUP_DIR/servers)" ]; then
                find $SETUP_DIR/servers/*.conf  -printf "%f\n"
            fi       
        fi    
        if [ -d "$SETUP_DIR/clients" ] ; then
            cd $SETUP_DIR/clients
            if [ "$(ls -A $SETUP_DIR/clients)" ]; then
                find $SETUP_DIR/clients/*.conf  -printf "%f\n"
            fi       
        fi    
        cd $SETUP_DIR
        exit 0
    else
        view_configuration $2
        exit 
    fi
fi
