#!/bin/bash

# VPN-Admin - A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# View system ipp.txt file which has client addresses.

# get system variables if needed
. ./vars

# make sure there is a Certificate Authority for this system.
#ca_check


# STEP 1 = Display ipp.txt file if avaialable

if [ -f "$SYSTEM_DIR/ipp.txt" ] ;
    then
        if [ $# -gt 0 ] ; 
            then
            if [ $1 == "FOLLOW" ] ; then
                sudo tail -f $SYSTEM_DIR/ipp.txt
            fi    
        else
            sudo cat $SYSTEM_DIR/ipp.txt
        fi        
    else
        printf "ERROR: OpenVPN system file: 'ipp.txt' not found.\n"
fi        
