#!/bin/bash

# VPN-Admin -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Update CRL and optionally copy to system and restart.

# get system variables if needed
. ./vars

# make sure there is a Certificate Authority for this system.
ca_check

# STEP 1 - See of crl.pem exist and if so copy to system.
if [ -f $SETUP_DIR/easyrsa3/pki/crl.pem ] ; 
    then
        sudo cp $SETUP_DIR/easyrsa3/pki/crl.pem $SYSTEM_DIR
    else
        printf "Run ./create-crl first.\n"
        exit 1
fi

# STEP 2 - Restart server if requested.
if [ "$1"  == "RESTART" ] ;
    then
        printf "Restarting OpenVPN system\n"
        sudo systemctl restart openvpn.service
fi
