#!/bin/bash

# VPN-Admin -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Update USB thumbdrive

# get system variables if needed
. ./vars

# make sure there is a Certificate Authority for this system.
ca_check

# make sure user has sudo access
sudo_check

# STEP 1 - check to see if certificate authority key exists
if [ ! -f ./easyrsa3/pki/private/ca.key ] ; then
    printf "
Error CA: ./easyrsa3/pki/private/ca.key does not exist
This is not a complete system.

Do you want to backup incomplete system? "

verify "(Yes/No) > "

    if [ $# -lt 1 ] ; then
            usage
            exit 1
    fi            
fi

# STEP 2 - see if mount point directory has been created
if [ ! -d $USB_MOUNT ] ; then
    sudo mkdir $USB_MOUNT 
fi

# STEP 3 - see if usb-thumdrive is connected
if [ ! -b $USB_DEV ] ; then
    printf "USB Thumbdrive not connected!\n"
    exit 1
fi

# STEP 4 - See if we should format this drive
# This can be a bit dangerous. Lets not advertize it.

# STEP 5 - mount thumbdrive if not mounted.
if  ! mount|grep $USB_MOUNT > /dev/null  ; then
    printf "Mounting USB-Thumbdrive.\n"
    sudo mount -t vfat $USB_DEV $USB_MOUNT
    if [ ! 0 -eq $? ] ; then
        printf "Error - Problem mounting USB-Thumbdrive\n" 
        exit 1
    fi
fi

# STEP 6 - remove secondary backup if a primary one exists.
#        - then move primary to seconday backup.
if [ -f $ZIPFILE ] ; then
    if [ -f $ZIPFILEBKUP ] ; then
        printf "Removing old secondary backup file.\n"
        sudo rm $ZIPFILEBKUP
    fi
    sudo mv $ZIPFILE $ZIPFILEBKUP
fi

# STEP 8 - Backup active current system to thumbdrive.
printf "Backing up entire system to $ZIPFILE.\n"
sudo zip -r $ZIPFILE *
if [ $? -ne 0 ] ; then
    rm -f $ZIPFILE 
    printf "ERROR: Update of USB Thumbdrive failed."
    exit 1
fi
    

# STEP 9 - Copy config file over to thumbdrive

printf "Updating system configuration files on thumbdrive.\n"
sudo rm -f $USB_MOUNT/*.conf
sudo rm -f $USB_MOUNT/*.ovpn
sudo rm -f $USB_MOUNT/crl.pem
if [ -d "$USB_MOUNT/ccd" ] ; 
    then
        sudo rm -f $USB_MOUNT/ccd/*
    else
        sudo mkdir $USB_MOUNT/ccd
fi               
sudo cp $SETUP_DIR/servers/* $USB_MOUNT/
sudo cp $SETUP_DIR/clients/* $USB_MOUNT/
sudo cp $SETUP_DIR/easyrsa3/pki/crl.pem $USB_MOUNT/
sudo cp $SETUP_DIR/ccd/* $USB_MOUNT/ccd/

# STEP 9 - Unmount thumbrive
printf "Unmounting USB Thumbdrive.\n"
sudo umount $USB_MOUNT
printf "USB Thumbdrive can be removed.\n"
