#!/bin/bash

# VPN-Admin -- A script base system for managing an OpenVPN system
#
# Copyright (C) 2018 by Matthew Dwight.
#
# This code released under version 3 of the GNU GPL; see COPYING and the
# LICENSE.GPL for this project for full licensing details.
#

# Don't do anything if we don't have easyras installed.
if [ ! -f ./easyrsa3/easyrsa ] ; then
    printf "Error: easyras3 has not been installed. \n"
    exit 1
fi

# Main directories for setup and system.
SETUP_DIR=$PWD
SYSTEM_DIR="/etc/openvpn"

# Thumbdrive for configuration backup and restore.
USB_DEV="/dev/sda1"
USB_MOUNT="/media/usb-thumbdrive"
UPDATE_DIR="$USB_MOUNT/vpn-setup"
UPDATE_DIR_BACKUP="$USB_MOUNT/vpn-setup-backup"
ZIPFILE="$UPDATE_DIR/vpn-setup.zip"


function verify {
    while true ; do
        if  [ $# -gt 0 ] ; then
            printf "$1"
        else
            printf "Verify 'YES' or 'NO' > "
        fi

        read USERINPUT

        if [[ -z "$USERINPUT" ]]; then
            continue
        fi
            
        if [ ${USERINPUT^^} == "YES" ] ; then
            printf 'YES\n'
            exit 0
	    fi
    	if [ ${USERINPUT^^} == "NO" ] ; then
    	    printf 'NO\n'
            exit 1
    	fi
    done
}

function ca_check {
    # see if system has been initialized and the CA created.
    if [ ! -f "$SETUP_DIR/easyrsa3/pki/ca.crt" ] ; then
        printf "ERROR: The system has not been initialized. Run ./build-new to initialize.\n" 
        exit 10
    fi              
    if [ ! -f "$SETUP_DIR/easyrsa3/pki/private/ca.key" ] ; then
        printf "ERROR: The keys have been removed.  Run ./restore-keys and try again.\n" 
        exit 11
    fi              
}    